"""
Low-level utilities for manipulating DOCX XML structures.
Contains normalization logic ported from Open-Xml-PowerTools concepts.
"""

import re
from typing import Any, Dict, Iterator, NamedTuple, Optional, Union

import structlog
from docx.document import Document as DocumentObject
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.table import Table, _Cell
from docx.text.paragraph import Paragraph
from docx.text.run import Run

logger = structlog.get_logger(__name__)


_CUSTOM_HEADING_NAME_RE = re.compile(r"Heading[ ]?([1-6])(?![0-9])")

# Cache qn() strings for massive performance gains in the extraction hot loop
QN_W_P = qn("w:p")
QN_W_R = qn("w:r")
QN_W_T = qn("w:t")
QN_W_DELTEXT = qn("w:delText")
QN_W_TAB = qn("w:tab")
QN_W_BR = qn("w:br")
QN_W_CR = qn("w:cr")
QN_W_RPR = qn("w:rPr")
QN_W_RPRCHANGE = qn("w:rPrChange")
QN_W_COMMENTREFERENCE = qn("w:commentReference")
QN_W_FOOTNOTEREFERENCE = qn("w:footnoteReference")
QN_W_ENDNOTEREFERENCE = qn("w:endnoteReference")
QN_W_FLDCHAR = qn("w:fldChar")
QN_W_FLDCHARTYPE = qn("w:fldCharType")
QN_W_INSTRTEXT = qn("w:instrText")
QN_W_INS = qn("w:ins")
QN_W_DEL = qn("w:del")
QN_W_ID = qn("w:id")
QN_W_AUTHOR = qn("w:author")
QN_W_DATE = qn("w:date")
QN_W_COMMENTRANGESTART = qn("w:commentRangeStart")
QN_W_COMMENTRANGEEND = qn("w:commentRangeEnd")
QN_W_HYPERLINK = qn("w:hyperlink")
QN_R_ID = qn("r:id")
QN_W_FLDSIMPLE = qn("w:fldSimple")
QN_W_INSTR = qn("w:instr")
QN_W_BOOKMARKSTART = qn("w:bookmarkStart")
QN_W_NAME = qn("w:name")
QN_W_SDT = qn("w:sdt")
QN_W_SMARTTAG = qn("w:smartTag")
QN_W_SDTCONTENT = qn("w:sdtContent")
QN_W_B = qn("w:b")
QN_W_I = qn("w:i")
QN_W_VAL = qn("w:val")
QN_W_PPR = qn("w:pPr")
QN_W_PSTYLE = qn("w:pStyle")
QN_W_OUTLINELVL = qn("w:outlineLvl")
QN_W_NUMPR = qn("w:numPr")
QN_W_NUMID = qn("w:numId")
QN_W_ILVL = qn("w:ilvl")
QN_W_DRAWING = qn("w:drawing")
QN_W_TC = qn("w:tc")
QN_W_OBJECT = qn("w:object")
QN_W_PICT = qn("w:pict")
QN_WP_DOCPR = qn("wp:docPr")
QN_V_IMAGEDATA = "{urn:schemas-microsoft-com:vml}imagedata"
QN_O_TITLE = "{urn:schemas-microsoft-com:office:office}title"


def is_heading_paragraph(
    paragraph: Paragraph,
    style_cache: Optional[dict] = None,
    default_pstyle: Optional[str] = None,
) -> bool:
    """
    Returns True iff `paragraph` projects with a Markdown heading prefix
    ('# ' through '###### '). Used by ingest and the mapper to decide
    whether to strip leading whitespace-only runs (which would otherwise
    project as '## \nText' instead of '## Text').
    """
    prefix = get_paragraph_prefix(paragraph, style_cache, default_pstyle)
    if not prefix:
        return False
    stripped = prefix.rstrip()
    return bool(stripped) and stripped == "#" * len(stripped)


def is_native_heading(
    paragraph: Paragraph,
    style_cache: Optional[dict] = None,
    default_pstyle: Optional[str] = None,
) -> bool:
    """
    Returns True if the paragraph is a native heading (Outline Level 0-8 or Heading style),
    excluding heuristic headings.
    """
    if style_cache is None:
        style_cache, default_pstyle = _get_style_cache(paragraph.part)
    p_el = paragraph._element
    pPr = p_el.find(QN_W_PPR)

    # 1. Outline Level
    if pPr is not None:
        oLvl = pPr.find(QN_W_OUTLINELVL)
        if oLvl is not None:
            val = oLvl.get(QN_W_VAL)
            if val and val.isdigit():
                lvl = int(val)
                if 0 <= lvl <= 8:
                    return True

    # 2. Style Name
    style_id = default_pstyle
    if pPr is not None:
        pStyle = pPr.find(QN_W_PSTYLE)
        if pStyle is not None:
            style_id = pStyle.get(QN_W_VAL) or default_pstyle

    style_info = style_cache.get(style_id) if style_cache and style_id else None

    if style_info:
        lvl = style_info.get("outline_level")
        if lvl is not None and 0 <= lvl <= 8:
            return True

    style_name = style_info["name"] if style_info else None

    if style_name and style_name.startswith("Heading"):
        return True
    if style_name == "Title":
        return True
    if style_name and style_name != "Normal":
        if _detect_heading_level_from_name(style_name) is not None:
            return True

    return False


def _detect_heading_level_from_name(name: str) -> Optional[int]:
    """
    Last-resort fallback: returns 1..6 if the style name contains a
    'Heading N' token (case-sensitive, anchored on a non-digit boundary
    after N). Used when a custom style was generated by Word's
    'Save Selection as a New Quick Style' flow without a basedOn link
    or explicit outlineLvl.

    Examples:
      'StyleHeading2NotItalicBefore0pt' -> 2
      'MyHeading3'                      -> 3
      'Heading10Custom'                 -> None  (digit boundary blocks it)
      'SubHeadingCallout'               -> None  (no digit after Heading)
      'heading 2'                       -> None  (we leave the regular
                                                  startswith('Heading')
                                                  path to handle this —
                                                  it's the canonical
                                                  python-docx name)
    """
    if not name:
        return None
    m = _CUSTOM_HEADING_NAME_RE.search(name)
    if not m:
        return None
    return int(m.group(1))


def _get_style_cache(part):
    """
    Parses styles.xml natively and builds an O(1) dictionary cache of styles.
    Bypasses the extreme overhead of python-docx's lazy-loading style wrappers.
    """
    pkg = part.package
    if hasattr(pkg, "_adeu_style_cache"):
        return pkg._adeu_style_cache

    cache: Dict[str, Any] = {}
    default_pstyle = None
    main_part = pkg.main_document_part

    try:
        styles_xml = main_part.styles.element
    except Exception:
        pkg._adeu_style_cache = (cache, None)
        return cache, None

    raw_styles = {}
    # 1. Parse raw XML elements
    for s in styles_xml.findall(qn("w:style")):
        s_id = s.get(qn("w:styleId"))
        if not s_id:
            continue

        s_type = s.get(qn("w:type"))
        is_default = s.get(qn("w:default")) in ("1", "true", "on")

        if s_type == "paragraph" and is_default:
            default_pstyle = s_id

        name_el = s.find(qn("w:name"))
        name = name_el.get(qn("w:val")) if name_el is not None else s_id

        based_on_el = s.find(qn("w:basedOn"))
        based_on = based_on_el.get(qn("w:val")) if based_on_el is not None else None

        outline_lvl = None
        num_id = None
        num_ilvl = None
        pPr = s.find(qn("w:pPr"))
        if pPr is not None:
            oLvl = pPr.find(qn("w:outlineLvl"))
            if oLvl is not None:
                val = oLvl.get(qn("w:val"))
                if val and val.isdigit():
                    outline_lvl = int(val)
            # Style-level list binding: Word's built-in "List Bullet" /
            # "List Number" styles carry <w:numPr> in styles.xml, not on the
            # paragraph. Without this, style-based lists project as plain
            # paragraphs and the agent loses ordered-vs-unordered semantics
            # (QA 2026-07-18 M4).
            numPr = pPr.find(qn("w:numPr"))
            if numPr is not None:
                numId_el = numPr.find(qn("w:numId"))
                if numId_el is not None:
                    n_val = numId_el.get(qn("w:val"))
                    if n_val and n_val != "0":
                        num_id = n_val
                ilvl_el = numPr.find(qn("w:ilvl"))
                if ilvl_el is not None:
                    i_val = ilvl_el.get(qn("w:val"))
                    if i_val and i_val.isdigit():
                        num_ilvl = int(i_val)

        bold = None
        rPr = s.find(qn("w:rPr"))
        if rPr is not None:
            b = rPr.find(qn("w:b"))
            if b is not None:
                val = b.get(qn("w:val"))
                bold = val not in ("0", "false", "off")

        raw_styles[s_id] = {
            "name": name,
            "based_on": based_on,
            "outline_level": outline_lvl,
            "bold": bold,
            "num_id": num_id,
            "num_ilvl": num_ilvl,
        }

    # 2. Recursively resolve inheritance chains
    def resolve_style(s_id, visited):
        if s_id in cache:
            return cache[s_id]
        if s_id in visited or s_id not in raw_styles:
            return {"name": s_id, "outline_level": None, "bold": False, "num_id": None, "num_ilvl": None}

        visited.add(s_id)
        raw = raw_styles[s_id]
        based_on_id = raw["based_on"]

        if based_on_id:
            parent = resolve_style(based_on_id, visited)
            o_lvl = raw["outline_level"] if raw["outline_level"] is not None else parent["outline_level"]
            bold_val = raw["bold"] if raw["bold"] is not None else parent["bold"]
            n_id = raw["num_id"] if raw["num_id"] is not None else parent.get("num_id")
            n_ilvl = raw["num_ilvl"] if raw["num_ilvl"] is not None else parent.get("num_ilvl")
        else:
            o_lvl = raw["outline_level"]
            bold_val = raw["bold"] if raw["bold"] is not None else False
            n_id = raw["num_id"]
            n_ilvl = raw["num_ilvl"]

        resolved = {
            "name": raw["name"],
            "outline_level": o_lvl,
            "bold": bold_val,
            "num_id": n_id,
            "num_ilvl": n_ilvl,
        }
        cache[s_id] = resolved
        return resolved

    for s_id in raw_styles:
        resolve_style(s_id, set())

    pkg._adeu_style_cache = (cache, default_pstyle)
    return cache, default_pstyle


def _get_numbering_cache(part) -> Dict[str, Dict[int, str]]:
    """
    Parses word/numbering.xml once per package into
    {numId: {ilvl: numFmt}} (e.g. {"5": {0: "decimal", 1: "lowerLetter"}}).

    Used to distinguish bullet lists from ordered lists in the projection
    (QA 2026-07-18 M4). Missing part / malformed XML yields an empty cache,
    which projects every list with the bullet marker (the historical default).
    """
    pkg = part.package
    if hasattr(pkg, "_adeu_numbering_cache"):
        return pkg._adeu_numbering_cache

    cache: Dict[str, Dict[int, str]] = {}
    numbering_root = None
    try:
        for p in pkg.parts:
            if str(p.partname).endswith("/numbering.xml"):
                if hasattr(p, "element"):
                    numbering_root = p.element
                else:
                    from docx.oxml import parse_xml

                    numbering_root = parse_xml(p.blob)
                break
    except Exception:
        numbering_root = None

    if numbering_root is not None:
        abstract_fmts: Dict[str, Dict[int, str]] = {}
        for abstract in numbering_root.findall(qn("w:abstractNum")):
            a_id = abstract.get(qn("w:abstractNumId"))
            if a_id is None:
                continue
            lvl_map: Dict[int, str] = {}
            for lvl in abstract.findall(qn("w:lvl")):
                ilvl_val = lvl.get(qn("w:ilvl"))
                fmt_el = lvl.find(qn("w:numFmt"))
                if ilvl_val is not None and ilvl_val.lstrip("-").isdigit() and fmt_el is not None:
                    fmt = fmt_el.get(qn("w:val"))
                    if fmt:
                        lvl_map[int(ilvl_val)] = fmt
            abstract_fmts[a_id] = lvl_map

        for num in numbering_root.findall(qn("w:num")):
            n_id = num.get(qn("w:numId"))
            a_ref = num.find(qn("w:abstractNumId"))
            if n_id is None or a_ref is None:
                continue
            a_id = a_ref.get(qn("w:val"))
            if a_id in abstract_fmts:
                cache[n_id] = abstract_fmts[a_id]

    pkg._adeu_numbering_cache = cache
    return cache


def get_list_marker(paragraph_part, num_id: Optional[str], ilvl: int) -> str:
    """
    Markdown marker for a list paragraph: '* ' for bullets, '1. ' for every
    numbered format (Markdown renderers renumber sequentially). Unknown
    numbering (no numbering.xml entry) keeps the historical '* '.
    """
    fmt = None
    if num_id is not None:
        lvl_map = _get_numbering_cache(paragraph_part).get(num_id)
        if lvl_map:
            fmt = lvl_map.get(ilvl)
            if fmt is None and lvl_map:
                # Fall back to the nearest defined level at or below ilvl.
                for lookup in range(ilvl, -1, -1):
                    if lookup in lvl_map:
                        fmt = lvl_map[lookup]
                        break
    if fmt is not None and fmt != "bullet":
        return "1. "
    return "* "


# --- Types ---
class DocxEvent(NamedTuple):
    type: str  # 'start', 'end', 'ref' (for comments); 'ins_start', etc.
    id: str
    author: Optional[str] = None
    date: Optional[str] = None


ParagraphItem = Union[Run, DocxEvent]


class NotesPart:
    def __init__(self, part, note_type="fn"):
        from docx.oxml import parse_xml

        self.part = part
        if not hasattr(part, "_adeu_element"):
            part._adeu_element = parse_xml(part.blob)
        self._element = part._adeu_element
        self.note_type = note_type


class FootnoteItem:
    def __init__(self, element, parent, note_type="fn"):
        self._element = element
        self._parent = parent
        self.part = parent.part
        self.id = element.get(qn("w:id"))
        self.note_type = note_type


def create_element(name: str):
    return OxmlElement(name)


def create_attribute(element, name: str, value: str):
    element.set(qn(name), value)


def _is_page_instr(instr: str) -> bool:
    if not instr:
        return False
    instr = instr.upper().strip()
    parts = instr.split()
    if not parts:
        return False
    return parts[0] in ("PAGE", "NUMPAGES")


def get_paragraph_prefix(
    paragraph: Paragraph,
    style_cache: Optional[dict] = None,
    default_pstyle: Optional[str] = None,
) -> str:
    """
    Returns the Markdown prefix for a paragraph based on its style.
    Uses the Fast XML Cache to avoid python-docx performance penalties.
    """
    if style_cache is None:
        style_cache, default_pstyle = _get_style_cache(paragraph.part)
    cache = style_cache
    p_el = paragraph._element
    pPr = p_el.find(QN_W_PPR)

    # 1. Check Outline Level on the paragraph itself (Structural Truth)
    if pPr is not None:
        oLvl = pPr.find(QN_W_OUTLINELVL)
        if oLvl is not None:
            val = oLvl.get(QN_W_VAL)
            if val and val.isdigit():
                lvl = int(val)
                if 0 <= lvl <= 8:
                    return "#" * (lvl + 1) + " "

    # 2. Get Style Name & properties from Cache
    style_id = default_pstyle
    if pPr is not None:
        pStyle = pPr.find(QN_W_PSTYLE)
        if pStyle is not None:
            style_id = pStyle.get(QN_W_VAL) or default_pstyle

    style_info = cache.get(style_id) if style_id else None

    if style_info:
        lvl = style_info.get("outline_level")
        if lvl is not None and 0 <= lvl <= 8:
            return "#" * (lvl + 1) + " "

    style_name = style_info["name"] if style_info else None

    # Check Style Name explicitly
    if style_name and style_name.startswith("Heading"):
        try:
            level = int(style_name.replace("Heading", "").strip())
            return "#" * level + " "
        except ValueError:
            pass

    if style_name == "Title":
        return "# "

    # 3. Check for List Formatting (direct paragraph numPr first, then the
    # style chain — Word's built-in List Bullet/List Number styles keep their
    # numPr in styles.xml, QA 2026-07-18 M4).
    list_num_id = None
    list_ilvl = None
    numbering_disabled = False
    if pPr is not None:
        numPr = pPr.find(QN_W_NUMPR)
        if numPr is not None:
            numId = numPr.find(QN_W_NUMID)
            if numId is not None:
                val = numId.get(QN_W_VAL)
                if val == "0":
                    # ECMA-376 §17.9.15: a direct numId of 0 REMOVES the
                    # numbering a style would otherwise apply.
                    numbering_disabled = True
                elif val:
                    list_num_id = val
                    ilvl = numPr.find(QN_W_ILVL)
                    if ilvl is not None:
                        val_attr = ilvl.get(QN_W_VAL)
                        if val_attr is not None and val_attr.isdigit():
                            list_ilvl = int(val_attr)
    if list_num_id is None and not numbering_disabled and style_info:
        style_num_id = style_info.get("num_id")
        if style_num_id:
            list_num_id = style_num_id
            if list_ilvl is None:
                list_ilvl = style_info.get("num_ilvl")
    if list_num_id is not None:
        level = list_ilvl if list_ilvl is not None else 0
        marker = get_list_marker(paragraph.part, list_num_id, level)
        return ("    " * level) + marker

    # 4. Custom heading style name fallback.
    if style_name and style_name != "Normal":
        custom_level = _detect_heading_level_from_name(style_name)
        if custom_level is not None:
            return "#" * custom_level + " "

    # 5. Heuristic for "Normal" style headers
    if style_name is None or style_name == "Normal":
        # Table cells must not be classified as heuristic headings
        ancestor = p_el.getparent()
        is_inside_table = False
        while ancestor is not None:
            if ancestor.tag == QN_W_TC:
                is_inside_table = True
                break
            ancestor = ancestor.getparent()

        if not is_inside_table:
            text = paragraph.text.strip()
            if text and len(text) < 100:
                is_all_caps = text.isupper()

                is_bold = False
                if style_info and style_info.get("bold"):
                    is_bold = True
                else:
                    # Check if the first visible run is explicitly bold in XML
                    runs = p_el.findall(f".//{QN_W_R}")
                    for r in runs:
                        t = r.find(f".//{QN_W_T}")
                        if t is not None and t.text and t.text.strip():
                            rPr_run = r.find(QN_W_RPR)
                            if rPr_run is not None:
                                b = rPr_run.find(QN_W_B)
                                if b is not None:
                                    val = b.get(QN_W_VAL)
                                    if val not in ("0", "false", "off"):
                                        is_bold = True
                            break

                if is_all_caps and is_bold:
                    return "## "

    return ""


def get_run_style_markers(run: Run, is_heading: Optional[bool] = None) -> tuple[str, str]:
    """
    Returns markdown prefix/suffix for run formatting (bold/italic).
    Bypasses `run.bold` and `run.italic` attributes for massive OXML performance gains.
    """
    prefix = ""
    suffix = ""

    # Check explicitly defined run properties in XML
    rPr = run._element.find(QN_W_RPR)
    is_bold = False
    is_italic = False

    if rPr is not None:
        b = rPr.find(QN_W_B)
        if b is not None:
            val = b.get(QN_W_VAL)
            if val not in ("0", "false", "off"):
                is_bold = True

        i = rPr.find(QN_W_I)
        if i is not None:
            val = i.get(QN_W_VAL)
            if val not in ("0", "false", "off"):
                is_italic = True

    if is_heading is None:
        parent = run._parent
        is_heading = is_native_heading(parent) if isinstance(parent, Paragraph) else False

    # Nesting order: Bold outer, Italic inner -> **_text_**
    if is_bold and not is_heading:
        prefix += "**"
        suffix = "**" + suffix

    if is_italic:
        prefix += "_"
        suffix = "_" + suffix

    return prefix, suffix


def split_boundary_whitespace(text: str) -> tuple[str, str, str]:
    """
    Splits `text` into (leading_ws, core, trailing_ws). Emphasis markers must
    wrap only the core: `**The Supplier **` (a bold run with a trailing space)
    is malformed Markdown — CommonMark requires the closing delimiter to hug
    non-whitespace — and it poisons every downstream CriticMarkup consumer
    (QA 2026-07-19 F-03/F-10). A fully-whitespace text yields ("", "", text)
    so callers skip the markers entirely.
    """
    core = text.strip()
    if not core:
        return "", "", text
    lead_len = len(text) - len(text.lstrip())
    return text[:lead_len], text[lead_len : lead_len + len(core)], text[lead_len + len(core) :]


def compute_change_pair_map(states_list) -> dict:
    """
    Maps each tracked-change id in a merged meta bubble to the OTHER ids of
    its resolution group, rendered ready for the bubble line suffix
    (`uid -> "Chg:2"` / `uid -> "Chg:2, Chg:3"`).

    A replacement is stored as a contiguous same-author <w:del> + <w:ins>
    pair with two distinct w:id values, but both engines resolve such a group
    as ONE unit — accepting or rejecting either side decides the whole
    replacement. Projecting the two ids side by side with no linkage implied
    they were independently resolvable (QA 2026-07-19 ADEU-QA-004); every
    meta-block builder (Python/Node ingest + mapper) uses this map to
    annotate grouped lines as `(pairs with Chg:N)`.

    Grouping mirrors the engines' `_get_paired_nodes` walk: consecutive
    ins/del ids in bubble order group while the author stays the same; any
    state carrying NO active ins/del (a comment- or format-only run between
    changes — physical text separating the elements) breaks the group.
    `states_list` entries are (ins_map, del_map, comments_set, fmt_map)
    snapshots in document order, as accumulated by the ingest/mapper state
    machines.
    """
    groups: list = []
    current: list = []
    seen_ids: set = set()

    for ins_map, del_map, _comments_set, _fmt_map in states_list:
        if not ins_map and not del_map:
            # A run with only comment/format meta sits between the tracked
            # elements: they are not siblings, the engine will not group them.
            if current:
                groups.append(current)
                current = []
            continue
        state_new = []
        for uid, meta in ins_map.items():
            if uid not in seen_ids:
                state_new.append((uid, getattr(meta, "author", None) or "Unknown"))
        for uid, meta in del_map.items():
            if uid not in seen_ids:
                state_new.append((uid, getattr(meta, "author", None) or "Unknown"))
        for uid, author in state_new:
            seen_ids.add(uid)
            if current and current[-1][1] != author:
                groups.append(current)
                current = []
            current.append((uid, author))
    if current:
        groups.append(current)

    pair_map: dict = {}
    for group in groups:
        if len(group) < 2:
            continue
        for uid, _author in group:
            others = ", ".join(f"Chg:{u}" for u, _a in group if u != uid)
            pair_map[uid] = others
    return pair_map


def apply_formatting_to_segments(text: str, prefix: str, suffix: str) -> str:
    """
    Applies formatting markers to text, ensuring newlines are excluded from the
    formatting and boundary whitespace stays OUTSIDE the markers.
    Examples: "**A\nB**" -> "**A**\n**B**";  bold "The Supplier " ->
    "**The Supplier** " (never "**The Supplier **").
    """
    if not prefix and not suffix:
        return text
    if not text:
        return ""

    def wrap(segment: str) -> str:
        lead, core, trail = split_boundary_whitespace(segment)
        if not core:
            return segment
        return f"{lead}{prefix}{core}{suffix}{trail}"

    if "\n" not in text:
        return wrap(text)

    parts = text.split("\n")
    return "\n".join(wrap(p) if p else "" for p in parts)


def iter_paragraph_content(paragraph: Paragraph) -> Iterator[ParagraphItem]:
    """
    Iterates over the content of a paragraph, yielding both Runs and Comment events.
    This allows reconstruction of text with inline comments using CriticMarkup.
    """
    # State for complex fields (w:fldChar)
    in_complex_field = False
    current_instr = ""
    hide_result = False

    def process_run_element(r_element):
        nonlocal in_complex_field, current_instr, hide_result

        c_id = None
        # Check for inline Tracked Formatting (w:rPrChange)
        rPr = r_element.find(QN_W_RPR)
        if rPr is not None:
            rPrChange = rPr.find(QN_W_RPRCHANGE)
            if rPrChange is not None:
                c_id = rPrChange.get(QN_W_ID)
                c_auth = rPrChange.get(QN_W_AUTHOR)
                c_date = rPrChange.get(QN_W_DATE)
                yield DocxEvent("fmt_start", c_id, c_auth, c_date)

        # Iterate children once to handle references, fields, and text
        for child in r_element:
            tag = child.tag
            if tag == QN_W_DRAWING or tag == QN_W_OBJECT:
                # Inline image/object: project a read-only marker so the agent
                # can see that a material element exists here (QA 2026-07-18
                # M5). id/date carry (docPr id, alt text) — the marker renders
                # as ![alt](docx-image:id).
                doc_pr = child.find(f".//{QN_WP_DOCPR}")
                alt = ""
                img_id = "0"
                if doc_pr is not None:
                    alt = doc_pr.get("descr") or doc_pr.get("title") or ""
                    img_id = doc_pr.get("id") or "0"
                yield DocxEvent("image", img_id, date=alt)
            elif tag == QN_W_PICT:
                # Legacy VML picture. Only actual images (v:imagedata) get a
                # marker; textpath-only shapes (watermarks) are reported by
                # sanitize's watermark audit instead of polluting the text.
                imagedata = child.find(f".//{QN_V_IMAGEDATA}")
                if imagedata is not None:
                    alt = imagedata.get(QN_O_TITLE) or ""
                    yield DocxEvent("image", "vml", date=alt)
            elif tag == QN_W_COMMENTREFERENCE:
                ref_id = child.get(QN_W_ID)
                if ref_id:
                    yield DocxEvent("ref", ref_id)
            elif tag == QN_W_FOOTNOTEREFERENCE:
                f_id = child.get(QN_W_ID)
                if f_id:
                    yield DocxEvent("footnote", f_id)
            elif tag == QN_W_ENDNOTEREFERENCE:
                e_id = child.get(QN_W_ID)
                if e_id:
                    yield DocxEvent("endnote", e_id)
            elif tag == QN_W_FLDCHAR:
                fld_type = child.get(QN_W_FLDCHARTYPE)
                if fld_type == "begin":
                    in_complex_field = True
                    current_instr = ""
                elif fld_type == "separate":
                    if _is_page_instr(current_instr):
                        hide_result = True
                    else:
                        parts = current_instr.strip().split()
                        if parts and parts[0] == "REF" and len(parts) > 1:
                            yield DocxEvent("xref_start", parts[1])
                elif fld_type == "end":
                    if not hide_result:
                        parts = current_instr.strip().split()
                        if parts and parts[0] == "REF" and len(parts) > 1:
                            yield DocxEvent("xref_end", parts[1])
                    in_complex_field = False
                    current_instr = ""
                    hide_result = False
            elif tag == QN_W_INSTRTEXT and in_complex_field and not hide_result:
                if child.text:
                    current_instr += child.text

        # Yield Run (if not hidden)
        if not hide_result:
            yield Run(r_element, paragraph)

        if c_id is not None:
            yield DocxEvent("fmt_end", c_id)

    def traverse_node(node):
        for child in node:
            tag = child.tag
            if tag == QN_W_R:
                # Standard run
                yield from process_run_element(child)
            elif tag == QN_W_INS:
                i_id = child.get(QN_W_ID)
                i_auth = child.get(QN_W_AUTHOR)
                i_date = child.get(QN_W_DATE)
                yield DocxEvent("ins_start", i_id, i_auth, i_date)
                yield from traverse_node(child)
                yield DocxEvent("ins_end", i_id)
            elif tag == QN_W_DEL:
                d_id = child.get(QN_W_ID)
                d_auth = child.get(QN_W_AUTHOR)
                d_date = child.get(QN_W_DATE)
                yield DocxEvent("del_start", d_id, d_auth, d_date)
                yield from traverse_node(child)
                yield DocxEvent("del_end", d_id)
            elif tag == QN_W_COMMENTRANGESTART:
                c_id = child.get(QN_W_ID)
                yield DocxEvent("start", c_id)
            elif tag == QN_W_COMMENTRANGEEND:
                c_id = child.get(QN_W_ID)
                yield DocxEvent("end", c_id)
            elif tag == QN_W_COMMENTREFERENCE:
                # Reference directly in paragraph
                pass
            elif tag == QN_W_HYPERLINK:
                rId = child.get(QN_R_ID)
                url = ""
                if rId and paragraph.part:
                    try:
                        rel = paragraph.part.rels[rId]
                        if rel.is_external:
                            url = rel.target_ref
                    except KeyError:
                        pass
                if url:
                    yield DocxEvent("hyperlink_start", rId, date=url)  # reuse date field for url
                yield from traverse_node(child)
                if url:
                    yield DocxEvent("hyperlink_end", rId, date=url)
            elif tag == QN_W_FLDSIMPLE:
                instr = child.get(QN_W_INSTR, "")
                target = ""
                if " REF " in instr or instr.startswith("REF "):
                    parts = instr.strip().split()
                    if len(parts) > 1 and parts[0] == "REF":
                        target = parts[1]
                if target:
                    yield DocxEvent("xref_start", target)
                yield from traverse_node(child)
                if target:
                    yield DocxEvent("xref_end", target)
            elif tag == QN_W_BOOKMARKSTART:
                b_name = child.get(QN_W_NAME)
                if b_name and (not b_name.startswith("_") or b_name.startswith("_Ref")):
                    yield DocxEvent("bookmark", b_name)
            elif tag in (QN_W_SDT, QN_W_SMARTTAG, QN_W_SDTCONTENT):
                yield from traverse_node(child)

    yield from traverse_node(paragraph._element)


def get_visible_runs(paragraph: Paragraph):
    """
    Iterates over runs in a paragraph, including those inside <w:ins> tags.
    Effectively returns the 'Accepted Changes' view of the runs.
    Filters out dynamic page number fields ({PAGE}, {NUMPAGES}).
    """
    return [item for item in iter_paragraph_content(paragraph) if isinstance(item, Run)]


def get_run_text(run: Run) -> str:
    """
    Extracts text from a run, converting <w:tab/> to spaces and <w:br/> to newlines.
    Standard run.text ignores these.
    """
    text = ""
    for child in run._element:
        if child.tag == QN_W_T or child.tag == QN_W_DELTEXT:
            # Fix 5.1: Normalize literal tabs to spaces to match w:tab behavior
            raw = child.text or ""
            text += raw.replace("\t", " ")
        elif child.tag == QN_W_TAB:
            text += " "  # Convert tab to space
        elif child.tag == QN_W_BR:
            if child.get(qn("w:type")) == "page":
                text += '<w:br w:type="page"/>'
            else:
                text += "\n"
        elif child.tag == QN_W_CR:
            text += "\n"
    return text


def _are_runs_identical(r1: Run, r2: Run) -> bool:
    """
    Compares two runs to see if they have identical formatting properties.
    """
    rPr1 = r1._r.rPr
    rPr2 = r2._r.rPr

    xml1 = rPr1.xml if rPr1 is not None else ""
    xml2 = rPr2.xml if rPr2 is not None else ""

    return xml1 == xml2


def _has_special_content(run: Run) -> bool:
    """
    Checks if the run contains elements that are not simple text, which would be lost
    during text-only coalescing (e.g. w:commentReference, w:drawing).
    """
    # Safe tags that are captured by run.text or are properties
    SAFE_TAGS = {
        qn("w:t"),
        qn("w:tab"),
        qn("w:br"),
        qn("w:cr"),
        qn("w:delText"),
        qn("w:rPr"),
    }

    for child in run._element:
        if child.tag not in SAFE_TAGS:
            return True
    return False


def _coalesce_runs_in_container(container_element, parent_paragraph):
    children = list(container_element)
    i = 0
    while i < len(children) - 1:
        curr = children[i]
        nxt = children[i + 1]

        if curr.tag == qn("w:r") and nxt.tag == qn("w:r"):
            r1 = Run(curr, parent_paragraph)
            r2 = Run(nxt, parent_paragraph)
            if not _has_special_content(r1) and not _has_special_content(r2):
                if _are_runs_identical(r1, r2):
                    # Find the last text node in the current run to merge into
                    last_t = None
                    for c in curr:
                        if c.tag in (qn("w:t"), qn("w:delText")):
                            last_t = c

                    for child in list(nxt):
                        if child.tag == qn("w:rPr"):
                            continue
                        if child.tag in (qn("w:t"), qn("w:delText")) and last_t is not None and last_t.tag == child.tag:
                            # Concatenate text instead of creating sibling text nodes
                            t1 = last_t.text or ""
                            t2 = child.text or ""
                            combined = t1 + t2
                            last_t.text = combined
                            if combined.strip() != combined:
                                last_t.set(qn("xml:space"), "preserve")
                        else:
                            curr.append(child)
                            if child.tag in (qn("w:t"), qn("w:delText")):
                                last_t = child
                    container_element.remove(nxt)
                    children.pop(i + 1)
                    continue

        if curr.tag in (
            qn("w:ins"),
            qn("w:del"),
            qn("w:hyperlink"),
            qn("w:sdt"),
            qn("w:smartTag"),
            qn("w:fldSimple"),
            qn("w:sdtContent"),
        ):
            _coalesce_runs_in_container(curr, parent_paragraph)

        i += 1

    if children and children[-1].tag in (
        qn("w:ins"),
        qn("w:del"),
        qn("w:hyperlink"),
        qn("w:sdt"),
        qn("w:smartTag"),
        qn("w:fldSimple"),
        qn("w:sdtContent"),
    ):
        _coalesce_runs_in_container(children[-1], parent_paragraph)


def _coalesce_runs_in_paragraph(paragraph: Paragraph):
    """
    Merges adjacent runs with identical formatting.
    This fixes issues where words are split like ["Con", "tract"] due to editing history.
    """
    _coalesce_runs_in_container(paragraph._element, paragraph)


def iter_document_parts(doc: DocumentObject):
    """
    Yields document parts in a linear order for processing:
    1. Unique Headers (Primary, First, Even)
    2. Main Body
    3. Unique Footers (Primary, First, Even)

    Handles 'Link to Previous' to avoid duplication.
    """
    for container, _kind in iter_document_parts_with_kind(doc):
        yield container


def iter_document_parts_with_kind(doc: DocumentObject):
    """
    Like iter_document_parts, but yields (container, kind) where kind is one
    of "header" / "body" / "footer" / "footnotes" / "endnotes".

    The kind sequence defines the document's structural part layout. The
    projection flattens all parts into one string, so diff/apply need these
    kinds to refuse (or correctly re-anchor) edits that would otherwise cross
    an OPC part boundary — the QA 2026-07-18 C1 failure wrote a final body
    paragraph into word/footer1.xml.
    """

    def _iter_section_parts(section, part_type_attr):
        # 1. Primary
        part = getattr(section, part_type_attr)
        if not part.is_linked_to_previous:
            yield part

        # 2. First Page
        if section.different_first_page_header_footer:
            first = getattr(section, f"first_page_{part_type_attr}")
            if not first.is_linked_to_previous:
                yield first

        # 3. Even Page
        if doc.settings.odd_and_even_pages_header_footer:
            even = getattr(section, f"even_page_{part_type_attr}")
            if not even.is_linked_to_previous:
                yield even

    # 1. Headers
    for section in doc.sections:
        for part in _iter_section_parts(section, "header"):
            yield part, "header"

    # 2. Main Body (The Document object itself acts as the container)
    yield doc, "body"

    # 3. Footers
    for section in doc.sections:
        for part in _iter_section_parts(section, "footer"):
            yield part, "footer"

    # 4. Footnotes & Endnotes (ordered)
    fn_part = None
    en_part = None
    for part in doc.part.package.parts:
        part_name = str(part.partname)
        if part_name.endswith("footnotes.xml"):
            fn_part = part
        elif part_name.endswith("endnotes.xml"):
            en_part = part

    if fn_part:
        yield NotesPart(fn_part, "fn"), "footnotes"
    if en_part:
        yield NotesPart(en_part, "en"), "endnotes"


def normalize_docx(doc: DocumentObject):
    """
    Applies normalization to a DOCX document to make text mapping reliable.
    1. Removes proof errors (spellcheck squiggles).
    2. Coalesces adjacent runs.
    """
    logger.info("Normalizing DOCX structure...")

    # Remove proof errors (spelling/grammar tags) via XPath
    for proof_err in doc.element.xpath("//w:proofErr"):
        proof_err.getparent().remove(proof_err)

    # Coalesce all parts (Headers, Body, Footers)
    # AND perform recursive coalescing for tables
    for part in iter_document_parts(doc):
        for item in iter_block_items(part):
            if isinstance(item, Paragraph):
                _coalesce_runs_in_paragraph(item)
            elif isinstance(item, Table):
                _normalize_table(item)


def _normalize_table(table: Table):
    for row in table.rows:
        for cell in row.cells:
            for item in iter_block_items(cell):
                if isinstance(item, Paragraph):
                    _coalesce_runs_in_paragraph(item)
                elif isinstance(item, Table):
                    _normalize_table(item)


def iter_block_items(parent) -> Iterator[Union[Paragraph, Table, FootnoteItem]]:
    """
    Yields Paragraph or Table objects in the order they appear in the XML.
    Supports Document, Header, Footer, and Cell objects.
    Recursion is left to the caller.
    """
    if isinstance(parent, DocumentObject):
        parent_elm = parent.element.body
    elif isinstance(parent, _Cell):
        parent_elm = parent._tc
    elif type(parent).__name__ == "NotesPart":
        tag = "w:footnote" if parent.note_type == "fn" else "w:endnote"
        for child in parent._element.findall(qn(tag)):
            if child.get(qn("w:type")) in ("separator", "continuationSeparator"):
                continue
            # Word reserves non-positive note ids (-1 separator, 0
            # continuation separator). Some generators omit the w:type
            # attribute on them, so filter by id as well — they must never
            # surface as user footnotes like "[^fn--1]:" (QA 2026-07-18 M6).
            note_id = child.get(qn("w:id"))
            try:
                if note_id is not None and int(note_id) <= 0:
                    continue
            except ValueError:
                pass
            yield FootnoteItem(child, parent, parent.note_type)
        return
    elif type(parent).__name__ == "FootnoteItem":
        parent_elm = parent._element
    else:
        # Header/Footer usually expose ._element or can be iterated
        if hasattr(parent, "_element"):
            parent_elm = parent._element
        else:
            raise ValueError(f"Unsupported parent type for iteration: {type(parent)}")

    for child in parent_elm.iterchildren():
        if child.tag == qn("w:p"):
            yield Paragraph(child, parent)
        elif child.tag == qn("w:tbl"):
            yield Table(child, parent)


def strip_bom_from_docx_bytes(data: bytes) -> bytes:
    """
    Reads a DOCX zip archive from bytes, strips the UTF-8 BOM (ef bb bf)
    from all XML and .rels files, and returns the sanitized ZIP archive bytes.
    """
    import io
    import zipfile

    if not data.startswith(b"PK\x03\x04"):
        raise ValueError("not a valid DOCX file (got bad zip signature)")

    in_stream = io.BytesIO(data)
    if not zipfile.is_zipfile(in_stream):
        raise ValueError("not a valid DOCX file (got bad zip signature)")

    out_stream = io.BytesIO()
    try:
        with zipfile.ZipFile(in_stream, "r") as z_in:
            if "[Content_Types].xml" not in z_in.namelist():
                raise ValueError("not a valid DOCX file (missing required Word parts)")
            with zipfile.ZipFile(out_stream, "w", zipfile.ZIP_DEFLATED) as z_out:
                for item in z_in.infolist():
                    content = z_in.read(item.filename)
                    if item.filename.endswith(".xml") or item.filename.endswith(".rels"):
                        if content.startswith(b"\xef\xbb\xbf"):
                            content = content[3:]
                    z_out.writestr(item, content)
        sanitized_bytes = out_stream.getvalue()
    except Exception as e:
        if isinstance(e, ValueError) and "not a valid DOCX file" in str(e):
            raise
        if isinstance(e, zipfile.BadZipFile):
            raise ValueError("not a valid DOCX file (got bad zip signature)") from e
        raise

    try:
        from docx import Document

        Document(io.BytesIO(sanitized_bytes))
    except Exception as e:
        if isinstance(e, ValueError) and "not a valid DOCX file" in str(e):
            raise
        raise ValueError("not a valid DOCX file (corrupted or invalid OOXML structure)") from e

    return sanitized_bytes
